import forms from "@tailwindcss/forms";

/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed-dim": "#c5cf38",
        "on-secondary-fixed-variant": "#2c5000",
        "inverse-surface": "#2e3132",
        "on-surface-variant": "#4b444f",
        "tertiary-fixed": "#e1eb53",
        "tertiary-container": "#3d4100",
        "primary-container": "#512d6d",
        "on-primary-container": "#c298e0",
        "secondary-fixed-dim": "#9dd761",
        "on-background": "#191c1d",
        "surface-container-lowest": "#ffffff",
        "inverse-primary": "#e1b6ff",
        "surface-container": "#edeeef",
        outline: "#7d7480",
        primary: "#3a1555",
        "outline-variant": "#cec3d0",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#0e2000",
        "surface-bright": "#f8f9fa",
        "surface-variant": "#e1e3e4",
        "on-tertiary-fixed": "#1b1d00",
        "error-container": "#ffdad6",
        error: "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "surface-tint": "#744e91",
        "surface-container-low": "#f3f4f5",
        "primary-fixed-dim": "#e1b6ff",
        tertiary: "#272a00",
        "secondary-fixed": "#b8f47a",
        surface: "#f8f9fa",
        "on-tertiary-fixed-variant": "#464a00",
        "primary-fixed": "#f2daff",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-container": "#b8f47a",
        "on-surface": "#191c1d",
        secondary: "#3c6a00",
        "on-tertiary-container": "#a7b115",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#2c0548",
        background: "#f8f9fa",
        "surface-dim": "#d9dadb",
        "inverse-on-surface": "#f0f1f2",
        "on-secondary-container": "#407100",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed-variant": "#5b3777",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "1rem",
        xl: "1.25rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        manrope: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [forms],
};
